#!/usr/bin/env bash
#
# Generated by: https://openapi-generator.tech
#

dotnet restore src/B3B4G7.SKS.Package.Services/ && \
    dotnet build src/B3B4G7.SKS.Package.Services/ && \
    echo "Now, run the following to start the project: dotnet run -p src/B3B4G7.SKS.Package.Services/B3B4G7.SKS.Package.Services.csproj --launch-profile web"
